[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "chromium"]

[phases.install]
cmds = [
  "cd server && npm install",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd server && npx prisma generate",
  "cd client && npm run build",
  "echo \"Chromium path: $(which chromium)\""
]

[start]
cmd = "cd server && npx prisma migrate deploy && node src/index.js"
